# Imports

In [75]:
import numpy as np
import pandas as pd

from scipy.spatial.distance import euclidean, cdist

# Load the data

In [34]:
india = pd.read_csv("../Data/India.csv", skiprows=2)
india['Month'] = pd.to_datetime(india['Month'], infer_datetime_format=True)
india = india.set_index(['Month'])
india.sort_index(inplace=True)
print(india.dtypes)
india.head()

what is vaping: (India)    int64
is vaping safe: (India)    int64
vaping shop: (India)       int64
vaping device: (India)     int64
dtype: object


what is vaping: (India)  is vaping safe: (India)  \
Month                                                          
2004-01-01                        0                        0   
2004-02-01                        0                        0   
2004-03-01                        0                        0   
2004-04-01                        0                        0   
2004-05-01                        0                        0   

            vaping shop: (India)  vaping device: (India)  
Month                                                     
2004-01-01                     0                       0  
2004-02-01                     0                       0  
2004-03-01                     0                       0  
2004-04-01                     0                       0  
2004-05-01                     0                       0

In [35]:
uk = pd.read_csv("../Data/UK.csv", skiprows=2)
uk['Month'] = pd.to_datetime(uk['Month'], infer_datetime_format=True)
uk = uk.set_index(['Month'])
uk.sort_index(inplace=True)
print(uk.dtypes)
uk.head()

what is vaping: (United Kingdom)    int64
is vaping safe: (United Kingdom)    int64
vaping shop: (United Kingdom)       int64
vaping device: (United Kingdom)     int64
dtype: object


what is vaping: (United Kingdom)  \
Month                                          
2004-01-01                                 0   
2004-02-01                                 0   
2004-03-01                                 0   
2004-04-01                                 0   
2004-05-01                                 0   

            is vaping safe: (United Kingdom)  vaping shop: (United Kingdom)  \
Month                                                                         
2004-01-01                                 0                              0   
2004-02-01                                 0                              0   
2004-03-01                                 0                              0   
2004-04-01                                 0                              0   
2004-05-01                                 0                              0   

            vaping device: (United Kingdom)  
Month                                        
2004-01-01                                0  
2004-02-01                                0  
2004-03-01                                0  
2004-04-01                                0  
2004-05-01                                0

In [36]:
usa = pd.read_csv("../Data/USA.csv", skiprows=2)
usa['Month'] = pd.to_datetime(usa['Month'], infer_datetime_format=True)
usa = usa.set_index(['Month'])
usa.sort_index(inplace=True)
print(usa.dtypes)
usa.head()

what is vaping: (United States)     int64
is vaping safe: (United States)     int64
vaping shop: (United States)        int64
vaping device: (United States)     object
dtype: object


what is vaping: (United States)  is vaping safe: (United States)  \
Month                                                                          
2004-01-01                                0                                0   
2004-02-01                                0                                0   
2004-03-01                                0                                0   
2004-04-01                                0                                0   
2004-05-01                                0                                0   

            vaping shop: (United States) vaping device: (United States)  
Month                                                                    
2004-01-01                             0                              0  
2004-02-01                             0                              0  
2004-03-01                             0                              0  
2004-04-01                             0                              0  
2004-05-01                             0                              0

# Preprocess

In [37]:
usa.replace({'<1': 0}, inplace=True)

# Similarity models

## DTW

In [43]:
# https://nipunbatra.github.io/blog/2014/dtw.html

## GAK

In [44]:
# https://web.sfc.wide.ad.jp/~kurosagi/public-posts/2017-04-11-global-alignment-kernels.html

## FastDTW

In [ ]:
# https://pypi.org/project/fastdtw/

In [62]:
from fastdtw import fastdtw

### Full Data

In [38]:
india_mat = india.values
uk_mat = uk.values
usa_mat = usa.values

In [39]:
distance, path = fastdtw(india_mat, uk_mat, dist=euclidean)
print("Distance between India and UK:", distance)

distance, path = fastdtw(india_mat, usa_mat, dist=euclidean)
print("Distance between India and USA:", distance)

distance, path = fastdtw(uk_mat, usa_mat, dist=euclidean)
print("Distance between UK and USA:", distance)

Distance between India and UK: 4917.9762267450105
Distance between India and USA: 3478.9266464043635
Distance between UK and USA: 3498.851288948


### Last 1 year

In [40]:
india_mat = india[india.index.year==2018].values
uk_mat = uk[uk.index.year==2018].values
usa_mat = usa[usa.index.year==2018].values

In [41]:
distance, path = fastdtw(india_mat, uk_mat, dist=euclidean)
print("Distance between India and UK:", distance)

distance, path = fastdtw(india_mat, usa_mat, dist=euclidean)
print("Distance between India and USA:", distance)

distance, path = fastdtw(uk_mat, usa_mat, dist=euclidean)
print("Distance between UK and USA:", distance)

Distance between India and UK: 821.8489756911822
Distance between India and USA: 625.7967125359412
Distance between UK and USA: 593.955035876165


## TSLearn

In [63]:
# https://tslearn.readthedocs.io/en/latest/gen_modules/tslearn.metrics.html

In [64]:
from tslearn.metrics import dtw_path

### Full Data

In [57]:
india_mat = india.values
uk_mat = uk.values
usa_mat = usa.values

In [58]:
path, distance = dtw_path(india_mat, uk_mat)
print("Distance between India and UK:", distance)

path, distance = dtw_path(india_mat, usa_mat)
print("Distance between India and USA:", distance)

path, distance = dtw_path(uk_mat, usa_mat)
print("Distance between UK and USA:", distance)

Distance between India and UK: 586.6208315428289
Distance between India and USA: 399.17038968340324
Distance between UK and USA: 427.67627944509616


### Last 1 year

In [59]:
india_mat = india[india.index.year==2018].values
uk_mat = uk[uk.index.year==2018].values
usa_mat = usa[usa.index.year==2018].values

In [60]:
path, distance = dtw_path(india_mat, uk_mat)
print("Distance between India and UK:", distance)

path, distance = dtw_path(india_mat, usa_mat)
print("Distance between India and USA:", distance)

path, distance = dtw_path(uk_mat, usa_mat)
print("Distance between UK and USA:", distance)

Distance between India and UK: 236.92825918408298
Distance between India and USA: 187.36328348958875
Distance between UK and USA: 173.38685071250356


# Averaging models

In [48]:
# https://tslearn.readthedocs.io/en/latest/gen_modules/tslearn.barycenters.html
# https://blog.acolyer.org/2016/05/13/dynamic-time-warping-averaging-of-time-series-allows-faster-and-more-accurate-classification/

# Clustering models

## TimeSeriesKMeans

In [99]:
# https://tslearn.readthedocs.io/en/latest/gen_modules/tslearn.clustering.html

In [61]:
from tslearn.clustering import TimeSeriesKMeans

### Full Data

In [72]:
india_mat = india.values
uk_mat = uk.values
usa_mat = usa.values

all_mat = np.array([india_mat, uk_mat, usa_mat])
all_mat

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        ...,
        [45, 39, 0, 38],
        [70, 29, 0, 24],
        [94, 55, 0, 23]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        ...,
        [53, 39, 46, 0],
        [58, 37, 34, 2],
        [49, 28, 31, 3]],

       [[0, 0, 0, '0'],
        [0, 0, 0, '0'],
        [0, 0, 0, '0'],
        ...,
        [90, 22, 8, '6'],
        [94, 19, 8, '7'],
        [100, 19, 9, '6']]], dtype=object)

In [77]:
km = TimeSeriesKMeans(n_clusters=2, metric="euclidean", max_iter=5, verbose=False, random_state=0).fit(all_mat)
print(km.cluster_centers_.shape)
print(km.labels_)

(2, 184, 4)
[0 1 0]


In [78]:
km = TimeSeriesKMeans(n_clusters=2, metric="dtw", max_iter=5, verbose=False, random_state=0).fit(all_mat)
print(km.cluster_centers_.shape)
print(km.labels_)

(2, 184, 4)
[0 1 0]


In [79]:
km = TimeSeriesKMeans(n_clusters=2, metric="softdtw", max_iter=5, verbose=False, random_state=0).fit(all_mat)
print(km.cluster_centers_.shape)
print(km.labels_)

(2, 184, 4)
[0 1 0]


### Last 1 year

In [80]:
india_mat = india[india.index.year==2018].values
uk_mat = uk[uk.index.year==2018].values
usa_mat = usa[usa.index.year==2018].values

all_mat = np.array([india_mat, uk_mat, usa_mat])
all_mat

array([[[74, 57, 0, 50],
        [85, 51, 0, 43],
        [68, 77, 0, 30],
        [85, 16, 0, 23],
        [91, 29, 0, 14],
        [35, 27, 0, 82],
        [79, 40, 0, 39],
        [55, 24, 0, 30],
        [24, 25, 0, 55],
        [45, 17, 0, 34],
        [55, 31, 0, 49],
        [67, 24, 0, 30]],

       [[63, 43, 47, 2],
        [55, 48, 44, 4],
        [65, 27, 46, 8],
        [47, 31, 59, 0],
        [40, 24, 39, 0],
        [53, 36, 33, 5],
        [44, 19, 50, 2],
        [77, 38, 55, 2],
        [60, 36, 52, 5],
        [58, 37, 40, 7],
        [53, 22, 23, 5],
        [60, 44, 49, 2]],

       [[91, 18, 12, '4'],
        [92, 16, 10, '3'],
        [81, 15, 9, '3'],
        [94, 20, 9, '4'],
        [76, 23, 9, '4'],
        [68, 19, 10, '4'],
        [61, 16, 10, '4'],
        [53, 26, 11, '2'],
        [81, 31, 8, '4'],
        [85, 23, 9, '4'],
        [96, 23, 9, '6'],
        [99, 24, 10, '5']]], dtype=object)

In [81]:
km = TimeSeriesKMeans(n_clusters=2, metric="euclidean", max_iter=5, verbose=False, random_state=0).fit(all_mat)
print(km.cluster_centers_.shape)
print(km.labels_)

(2, 12, 4)
[0 1 1]


In [82]:
km = TimeSeriesKMeans(n_clusters=2, metric="dtw", max_iter=5, verbose=False, random_state=0).fit(all_mat)
print(km.cluster_centers_.shape)
print(km.labels_)

(2, 12, 4)
[0 1 1]


In [83]:
km = TimeSeriesKMeans(n_clusters=2, metric="softdtw", max_iter=5, verbose=False, random_state=0).fit(all_mat)
print(km.cluster_centers_.shape)
print(km.labels_)

(2, 12, 4)
[0 1 1]


# Classification models

## KNeighborsTimeSeriesClassifier

In [100]:
# https://tslearn.readthedocs.io/en/latest/auto_examples/plot_neighbors.html
# https://tslearn.readthedocs.io/en/latest/gen_modules/tslearn.neighbors.html
# https://github.com/markdregan/K-Nearest-Neighbors-with-Dynamic-Time-Warping

In [85]:
from tslearn.neighbors import KNeighborsTimeSeriesClassifier

### Full Data

In [95]:
india_mat = india.values
uk_mat = uk.values
usa_mat = usa.values

In [96]:
clf = KNeighborsTimeSeriesClassifier(n_neighbors=1, metric="dtw")
clf.fit([india_mat, uk_mat], y=[0, 1])
clf.predict(usa_mat)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0])

### Last 1 year

In [97]:
india_mat = india[india.index.year==2018].values
uk_mat = uk[uk.index.year==2018].values
usa_mat = usa[usa.index.year==2018].values

In [98]:
clf = KNeighborsTimeSeriesClassifier(n_neighbors=1, metric="dtw")
clf.fit([india_mat, uk_mat], y=[0, 1])
clf.predict(usa_mat)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])